### ISSUE TITLE
Desk case

### ISSUE THREAD

**Issue by andypiper** [MXZZ/Netgotchi#3]
```
optional 3d printed parts ( from thingiverse.com)
```

I don't find anything there searching for Netgotchi, what model is being used for the case shown in the images?

**Comment by MXZZ** [comment]
Hi, as it works with different esp8266 models you just need to get a cover for your specific model and attach the screen. I ll be sharing mine once they are final but it will work with nodemcu v2 ( not ever v3) that is quite rare to obtain.

**Comment by MXZZ** [comment]
I 'm still hoping for someone to come up with a nicer version :-)

**Comment by porkcube** [comment]
I used [this one](https://www.printables.com/model/510481-terminal-for-ssd1306-096-oled-and-wemos-d1-mini) for Wemos D1 Mini w/0.96" display, there's a lot of existing cases if you search for your specific esp8266 variant and screen size on thingiverse/printables

**Comment by MXZZ** [comment]
thank you @porkcube , I added your link in the readme . closing this issue for now

**Comment by andypiper** [comment]
Sure, thank you. I was asking about the model from the images in the README, but at least linking to something else is helpful.
