### ISSUE TITLE
Repeated IP[0]

### ISSUE THREAD

**Issue by luizabbadia** [MXZZ/Netgotchi#4]
Love that, but just to add something, line 350 provokes repetition of IP[0]
String ipprefix = String(currentIP[0]) +"."+String(currentIP[1])+"."+String(currentIP[0])+".";
should be
String ipprefix = String(currentIP[0]) +"."+String(currentIP[1])+"."+String(currentIP[2])+".";

**Comment by luizabbadia** [comment]
Sorry, I need new glasses!

Em qui., 11 de jul. de 2024, 10:30, MXZZ ***@***.***>
escreveu:

**Comment by MXZZ** [comment]
no problem :)))
